language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: AH7F6eerECSEBd3CQVc1HuBahHCCQt1XCcZ8nBZerBhueDyzhXI3NvpG8ooyH71N9MF3RJaJ5wzWOMAPQyRn46puyPHuXY4Tp3OurLAUZ6GUP3/3LT86Vq0RjyrBYJe+eXPxR1u2NuSjpGacthl7ceWj68D2o5rePxZXpiLfP2Q=
  - secure: PdDDgN+QvwGT/I9rmbShvoNbbF6V41i9xtDbk1HpDooj1HXr/mZGriE55liftIQOTokS+pa0IArgiCKYjcRiKJgtvOWgvF4hSgdIvf08sRk9C5UTXIVzgzP7ORAcVzl4ilngurmPjMt+3AV16YPGHsLgZtIsdTgWVQLv86Z+UaE=
  - secure: VBVWkB/MscV4fDO7SGyMDGEHw05/3/CxmY/nXorem1xqClSbUJ/1j6HdifAlcjwWwJ7yq1jPkvyPbepNmfwEinpSqYBFUqac00dyxXMnnsymFP5IExTlihGqsgGh/y57W5oh+qcDzsrxjEtcbBtF+iPVWATdY4qJAPFizmo2r1g=
  - secure: BWk47ZpXxlNtfZok6hIcoRT/oouVMfjpCO0y5zRkbeUQ7uU59S+8DglqhFcyFZhyEr5nK66TlMnOqMQi8aoS6p0sYh5uhyma0PJdKTaR2FKQbeQ93kaTJ24NZt2TceQsfvQrAj1MWxWKegfsALXEYhZcxEilkMlivd4aNux1pDU=
